export enum PATH_SERVER_RESPONSE {
    ERROR_UNPROCESSABLE_ENTITY = 422,
    ERROR_CONFLICT = 409,
}

export enum RESULT_CODE_RESPONSE {
    SUCCESS = 0,
    REQUEST_INVALID = 1,
    REQUEST_INVALID_NEED_CAPTCHA = 10,

}
